### ISSUE TITLE
More potential related articles.

### ISSUE THREAD

**Issue by MaxChanger** [hehefan/Awesome-Dynamic-Point-Cloud-Analysis#1]
Thank you very much for your summary of point cloud + dynamic related fields, it is very beneficial for me.

Do you think *Point Cloud Scene Flow*, *LiDAR-Based Moving Object Segmentation* and *4D Panoptic LiDAR Segmentation*
 are subtasks under this topic? Maybe the point cloud-based scene flow tends to focus more on the motion of each point between the two frames, so I'm not quite sure if it still belongs to this topic.

> Some relevant references:
> - 4D Panoptic LiDAR Segmentation [arXiv](https://arxiv.org/abs/2102.12472), [github](https://github.com/MehmetAygun/4D-PLS)
> - LMNet: Moving Object Segmentation in 3D LiDAR Data [arXiv](https://arxiv.org/abs/2105.08971), [github](https://github.com/PRBonn/LiDAR-MOS)
> - https://github.com/MaxChanger/awesome-point-cloud-scene-flow

**Comment by hehefan** [comment]
Hi @MaxChanger,

3D scene flow estimation is mainly about two frames. When people refer to dynamic point clouds or point cloud videos / sequences, it is usually 3 three frames at least. I therefore do not include the task here.

Thank you for pointing out the relevant references.

Best.

**Comment by MaxChanger** [comment]
Thanks for your quick reply.
Perhaps, for LiDAR-based 4D Panoptic segmentation, LiDAR-based moving object segmentation and so on, if I found some new public methods about these, I will also synchronize again, or make a pull request if allowed.
